# These are supported funding model platforms
# github: [example-owner]
# patreon: # Replace with a single Patreon username
# ko_fi: # Replace with a single Ko-fi username
# open_collective: # Replace with a single Open Collective username
# buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
# custom: ['https://github.com/example-owner/wechat-mac-rpa'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
